sudo: required

arch:
  - amd64
  - arm64

services:
- docker

script:
- >
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
  docker build -t sakshi9715/kubeadm-version:$TRAVIS_BRANCH-$TRAVIS_CPU_ARCH .
  docker push sakshi9715/kubeadm-version:$TRAVIS_BRANCH-$TRAVIS_CPU_ARCH
  docker run --rm --name=kubeadm-version sakshi9715/kubeadm-version:$TRAVIS_BRANCH-$TRAVIS_CPU_ARCH kubeadm config images list
  else
  docker build -t sakshi9715/kubeadm-version:$TRAVIS_BRANCH .
  docker push sakshi9715/kubeadm-version:$TRAVIS_BRANCH
  docker run --rm --name=kubeadm-version sakshi9715/kubeadm-version:$TRAVIS_BRANCH kubeadm config images list
  fi
