sudo: required

arch:
  - amd64
  - arm64

services:
- docker

script:
- >
- if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
  arch="-$TRAVIS_CPU_ARCH";
  else
  arch="";
  fi
- docker build -t sakshi9715/kubeadm-version:$TRAVIS_BRANCH$TRAVIS_CPU_ARCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push sakshi9715/kubeadm-version:$TRAVIS_BRANCH$TRAVIS_CPU_ARCH
- docker run --rm --name=kubeadm-version sakshi9715/kubeadm-version:$TRAVIS_BRANCH$TRAVIS_CPU_ARCH kubeadm config images list
